version: '2'

volumes: {}

services:

  oereb-db:
    build: test-db
    image: camptocamp/oereb-db-dev
    volumes:
            - ./:/oereb
    # Uncomment following line to have database show all incoming SQL statements
    #command: postgres -c log_statement=all


  oereb-server:
    networks:
    - default
    - print-network
    build: .
    image: camptocamp/oereb-wsgi
    ports:
    - 6543:8080
    environment:
    - PRINT_SERVICE_HOST=oereb-print
    - PRINT_SERVICE_PORT=8080
    - POSTGRES_SERVICE_USER=postgres
    - POSTGRES_SERVICE_PASS=password
    - POSTGRES_SERVICE_HOST=oereb-db
    - POSTGRES_SERVICE_PORT=5432
    - POSTGRES_SERVICE_DATABASE=pyramid_oereb

networks:
  print-network:
    external: true
